//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int aid { get; set; }
        public string orgname { get; set; }
        public int eid { get; set; }
        public string empname { get; set; }
        public string dep { get; set; }
        public string service { get; set; }
        public int uid { get; set; }
        public string username { get; set; }
        public string pfname { get; set; }
        public string plname { get; set; }
        public Nullable<int> age { get; set; }
        public string gender { get; set; }
        public string phnum { get; set; }
        public string address { get; set; }
        public string date { get; set; }
        public string timeslot { get; set; }
        public string timeduration { get; set; }
        public string status { get; set; }
        public Nullable<int> ratings { get; set; }
    }
}
