//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HhcApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int eid { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string CNIC { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Qualification { get; set; }
        public string Experience { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string OrgName { get; set; }
        public string Department { get; set; }
        public string Status { get; set; }
        public Nullable<int> Oid { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
